import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metersRouter from "./meters";
import consumptionRouter from "./consumption";
import weatherRouter from "./weather";
import analysisRouter from "./analysis";
import swotRouter from "./swot";
import risksRouter from "./risks";
import seuRouter from "./seu";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import reportsRouter from "./reports";
import unitsRouter from "./units";
import unitTechnicalProfilesRouter from "./unit-technical-profiles";
import unitTechnicalProfileFieldDefinitionsRouter from "./unit-technical-profile-field-definitions";
import summaryRouter from "./summary";
import authRouter from "./auth";
import subUnitsRouter from "./sub-units";
import energySourcesRouter from "./energy-sources";
import equipmentRouter from "./equipment";
import equipmentFieldDefinitionsRouter from "./equipment-field-definitions";
import seedRouter from "./seed";
import targetsRouter from "./targets";
import companiesRouter from "./companies";
import companyProfileRouter from "./company-profile";
import companySettingsRouter from "./company-settings";
import companyBrandRouter from "./company-brand";
import companyReportSettingsRouter from "./company-report-settings";
import energyUseGroupsRouter from "./energy-use-groups";
import mgmRouter from "./mgm";
import variablesRouter from "./variables";
import seuAssessmentRouter from "./seu-assessment";
import energyPerformanceRouter from "./energy-performance";
import energyActionPlansRouter from "./energy-action-plans";
import energyTargetProgressRouter from "./energy-target-progress";
import vapProjectsRouter from "./vap-projects";
import energyReviewRouter from "./energy-review";
import energyReviewRecordsRouter from "./energy-review-records";
import pendingWorkItemsRouter from "./pending-work-items";
import auditEventsRouter from "./audit-events";
import metricsRouter from "./metrics";
import operationalDiagnosticsRouter from "./operational-diagnostics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(unitsRouter);
router.use(unitTechnicalProfilesRouter);
router.use(unitTechnicalProfileFieldDefinitionsRouter);
router.use(subUnitsRouter);
router.use(energySourcesRouter);
router.use(energyUseGroupsRouter);
router.use(equipmentRouter);
router.use(equipmentFieldDefinitionsRouter);
router.use(metersRouter);
router.use(consumptionRouter);
router.use(weatherRouter);
router.use(analysisRouter);
router.use(swotRouter);
router.use(risksRouter);
router.use(seuRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(reportsRouter);
router.use(summaryRouter);
router.use(seedRouter);
router.use(targetsRouter);
router.use(companiesRouter);
router.use(companyProfileRouter);
router.use(companySettingsRouter);
router.use(companyBrandRouter);
router.use(companyReportSettingsRouter);
router.use(mgmRouter);
router.use(variablesRouter);
router.use(seuAssessmentRouter);
router.use(energyPerformanceRouter);
router.use(energyActionPlansRouter);
router.use(energyTargetProgressRouter);
router.use(vapProjectsRouter);
router.use(energyReviewRouter);
router.use(energyReviewRecordsRouter);
router.use(pendingWorkItemsRouter);
router.use(auditEventsRouter);
router.use(metricsRouter);
router.use(operationalDiagnosticsRouter);

export default router;
